version: "3.8"

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: mem0
      POSTGRES_PASSWORD: mem0pass
      POSTGRES_DB: mem0db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    command: >
      bash -c "
        apt-get update &&
        apt-get install -y postgresql-server-dev-15 build-essential &&
        git clone https://github.com/pgvector/pgvector.git /tmp/pgvector &&
        cd /tmp/pgvector &&
        make install &&
        docker-entrypoint.sh postgres
      "

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    volumes:
      - ./backend:/app
    working_dir: /app
    command: uvicorn main:app --host 0.0.0.0 --port 5000 --reload
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://mem0:mem0pass@postgres:5432/mem0db
    depends_on:
      - postgres

  frontend:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  pgdata:
